jobs:
  - job: BuildArtifactsBackend
    displayName: "Build infrastructure Backend"
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: AzureCLI@2  
        displayName: 'build base bicep artifact' 
        inputs: 
          azureSubscription: ${{parameters.svcPrincipal}} 
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'  
          inlineScript: |
            az bicep build --file Infrastructure/Backend/infrastructurebe.bicep

      - task: PublishBuildArtifacts@1 
        displayName: 'Publish bicep artifact' 
        inputs: 
          PathtoPublish: '$(Build.SourcesDirectory)/Infrastructure/Backend'
          ArtifactName: 'infrastructureBackendDrop'  
          publishLocation: 'Container' 